#! /usr/bin/env python

import glob
import subprocess

files = []
for path in ["."]:
    inPath = glob.glob(path + "/*.markdown")
    inPath.sort()
    files.extend(inPath)
    

head = '''\
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="description" content="A short course on programming microcontrollers using Arduino" />
        <meta name="author" content="Joe Turner" />
        <title>Microcontroller Programming</title>
        <link rel="stylesheet" href="normalize.css"/>
        <link rel="stylesheet" href="main.css"/>
        <link rel="stylesheet" href="tango.css"/>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
        <script src="font-color-inliner.js"></script>
    </head>
    <body class="codehilite">
'''

body = ""
for filename in files:
    body += subprocess.check_output(["markdown.rb", filename]) 
#    with open(filename) as f:
#        body += markdown2.markdown(f.read(),  extras=["fenced-code-blocks",
#                                                      "code-friendly"])

tail = '''\
    </body>
</html>
'''

f = open("html/index.html", "w")
f.write(head)
f.write(body)#.encode('utf8', 'replace'))
f.write(tail)
f.close()

subprocess.call(["weasyprint", "html/index.html", "pdf/python.pdf"])
